#!/usr/bin/env bash
# displays numbers from 1 to 100 
# displays FizzBuzz instead of the number which is multiple of 3 and 5
# displays Fizz instead of the number which is multiple of 3
# display Buzz instead of the number which is multiple of 5
i=1
for ((i=1; i<=100; i++))
do
    if [[ $((i%3)) -eq 0 && $((i%5)) -eq 0 ]]
    then
        echo "FizzBuzz"
        continue

    elif [ $((i%3)) -eq 0 ]
    then
        echo "Fizz"
        continue

    elif [ $((i%5)) -eq 0 ]
    then
        echo "Buzz"
        continue

    else
        echo $i
    fi
done
